# Generated by Django 3.1.7 on 2021-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix_article', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nom_client', models.CharField(max_length=100)),
                ('adresse_client', models.CharField(max_length=150)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en cours', 'en cours'), ('livré', 'livré'), ('retour', 'retour')], default='en cours', max_length=20)),
                ('date_statut', models.DateTimeField(auto_now_add=True)),
                ('prix_livraison', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('article', models.ManyToManyField(related_name='article', to='doortodoor.Article')),
            ],
        ),
    ]
