# Generated by Django 3.1.7 on 2021-03-18 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('nom_client', models.CharField(max_length=100)),
                ('adresse_client', models.CharField(max_length=150)),
                ('contact_client', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en cours', 'en cours'), ('livré', 'livré'), ('retour', 'retour')], default='en cours', max_length=20)),
                ('date_statut', models.DateTimeField(auto_now_add=True)),
                ('prix_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('article', models.ManyToManyField(related_name='article', to='doortodoor.Article')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
