# Generated by Django 3.1.7 on 2021-03-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
