# Generated by Django 3.1.7 on 2021-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
