# Generated by Django 3.1.7 on 2021-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0002_auto_20210318_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
