# Generated by Django 3.1.7 on 2021-03-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0002_auto_20210316_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='prix_article',
            new_name='prix',
        ),
    ]
