# Generated by Django 3.1.7 on 2021-03-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doortodoor', '0002_delete_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en cours', 'en cours'), ('livré', 'livré'), ('retour', 'retour')], default='en cours', max_length=20)),
                ('date_statut', models.DateTimeField(auto_now_add=True)),
                ('prix_livraison', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('article', models.ManyToManyField(related_name='article', to='doortodoor.Article')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
