# Generated by Django 3.1.7 on 2021-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0003_auto_20210318_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='montant_livraison',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_article',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='prix_livraison',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
