# Generated by Django 3.1.7 on 2021-03-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0003_auto_20210316_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
    ]
