# Generated by Django 3.1.7 on 2021-03-16 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doortodoor', '0004_remove_article_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='user',
        ),
        migrations.AddField(
            model_name='livraison',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
