# Generated by Django 3.1.7 on 2021-03-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0004_auto_20210329_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
