# Generated by Django 3.1.7 on 2021-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0005_auto_20210316_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
