# Generated by Django 3.1.7 on 2021-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doortodoor', '0005_remove_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='montant_livraison',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_article',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='prix_livraison',
            field=models.IntegerField(blank=True),
        ),
    ]
